# volumes:
volumes:
    tripager:
        external: true
services:
  db:
    build:
        context: ./relational-data
        dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER= tripager
        - POSTGRES_DB= tripager
        - POSTGRES_PASSWORD= tripager
    ports:
        - 15432:5432
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://tripager:tripager@db/tripager
      WAIT_HOSTS: postgres:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
