# volumes:
volumes:
  tripager-data:
      external: true
  # pg-admin:
  #     external: true
services:
  api:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://tripager:tripager@db/tripager-data
      # WAIT_HOSTS: postgres:5432       took this away for ghi container to work
  db:
    build:
        context: ./relational-data
        dockerfile: ./Dockerfile.dev
    volumes:
        - tripager-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: tripager
        POSTGRES_USER: tripager
        POSTGRES_DB: tripager
    ports:
        - 15432:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
  # pg-admin:
  #   image: dpage/pgadmin4
  #   volumes:
  #     - pg-admin:/var/lib/pgadmin
  #   ports:
  #     - 8082:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: tripager@tripager.com
  #     PGADMIN_DEFAULT_PASSWORD: tripager
  #     PGADMIN_DISABLE_POSTFIX: 1
